file:F:/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:F:/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:F:/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:F:/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:F:/Git/etc/gitconfig	filter.lfs.required=true
file:F:/Git/etc/gitconfig	http.sslbackend=openssl
file:F:/Git/etc/gitconfig	http.sslcainfo=F:/Git/mingw64/etc/ssl/certs/ca-bundle.crt
file:F:/Git/etc/gitconfig	core.autocrlf=true
file:F:/Git/etc/gitconfig	core.fscache=true
file:F:/Git/etc/gitconfig	core.symlinks=false
file:F:/Git/etc/gitconfig	pull.rebase=false
file:F:/Git/etc/gitconfig	credential.helper=manager
file:F:/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:F:/Git/etc/gitconfig	init.defaultbranch=master
file:C:/Users/Akbar/.gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/Akbar/.gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/Akbar/.gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Users/Akbar/.gitconfig	filter.lfs.required=true
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	remote.origin.url=https://github.com/Codex2142/TusParking.git
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config	branch.main.remote=origin
file:.git/config	branch.main.merge=refs/heads/main
